[package]
name = "strata"
version = "0.1.0"
edition = "2024"

[features]
error = ["dep:thiserror"]
serde = ["dep:serde"]
time = ["dep:time"]

[dependencies]
serde = { version = "1", features = ["derive"], optional = true }
thiserror = { version = "2", optional = true }
time = { version = "0.3", features = ["formatting", "macros", "parsing"], optional = true }
