[package]
name = "strata-axum"
version = "0.1.0"
edition.workspace = true

[dependencies]
strata = { path = "../strata", features = ["time"] }
strata-error = { path = "../strata-error" }

axum = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }